require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "astro",
    "bash",
    "c",
    "cpp",
    "css",
    "dockerfile",
    "go",
    "html",
    "java",
    "javascript",
    "json",
    "latex",
    "lua",
    "markdown",
    -- "php",
    "python",
    "rust",
    "regex",
    "rust",
    "scss",
    "sql",
    "typescript",
    "vue",
    "yaml",
  },
  sync_install = true, -- install languages synchronously (only applied to `ensure_installed`)
  ignore_install = {},
  highlight = {
    enable = true,
    disable = {},
    additional_vim_regex_highlighting = false,
  },
})
